steps:
  - id: get-kube-config
    dir: hello-cloudbuild-v2
    name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_CORE_PROJECT=$PROJECT_ID
      - CLOUDSDK_COMPUTE_REGION=${_REGION}
      - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
      - KUBECONFIG=/workspace/.kube/config
    args:
      - cluster-info

  - id: deploy
    dir: hello-cloudbuild-v2
    name: gcr.io/gitops-lab-394015/helm:3.12.0
    env:
      - KUBECONFIG=/workspace/.kube/config
    args:
      - upgrade
      - --install
      - --create-namespace
      - ${TAG_NAME}-demo
      - --namespace=${TAG_NAME}-demo
      - --values
      - k8s/demo/${TAG_NAME}-values.yaml
      - --set
      - container.image=${_REGION}-docker.pkg.dev/$PROJECT_ID/demo/demo
      - --set
      - container.tag=${COMMIT_SHA}
      - ./k8s/demo
