steps:
    dir: hello-cloudbuild-v2
    name: gcr.io/gitops-lab-394015/helm:3.12.0
    env:
      - KUBECONFIG=/workspace/.kube/config
    args:
      - upgrade
      - --install
      - --create-namespace
      - ${TAG_NAME}-demo
      - --namespace=${TAG_NAME}-demo
      - --values
      - k8s/demo/${TAG_NAME}-values.yaml
      - --set
      - container.image=${_REGION}-docker.pkg.dev/$PROJECT_ID/demo/demo
      - --set
      - container.tag=${COMMIT_SHA}
      - ./k8s/demo
